# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f9156d6a158d94423f4e5dfb468674ad35d3203e30c47c55f547ef87b471062c5f12960034e632c77cd74d4ad9670e6854c479939cda9fd7db38ffbf3d18cd

test:
  secret_key_base: 0eb5d61b488c258735a538b00a432ceb5ac427274125941ecdf0d173b212a2c12aa4afccb41995f878472e4cef2006b66cd3a05dc58ce2d4229404a0d5495698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
